source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :development do
  gem 'rake',           '>= 10.4',  :require => false
  gem 'puppet',         '~> 6.0',   :require => false
  gem 'puppet-strings', '~> 2.5.0', :require => false
end
